// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: gdx/edge/v1/edge.proto

package v1

import (
	v1 "github.com/gq-godark/gdx-go-sdk/proto/gdx/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (edge-authenticated user).
	UserUuid    []byte         `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	SymbolId    uint64         `protobuf:"varint,2,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	RequestType v1.RequestType `protobuf:"varint,3,opt,name=request_type,json=requestType,proto3,enum=gdx.common.v1.RequestType" json:"request_type,omitempty"`
	Nonce       uint64         `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BodyLength  uint32         `protobuf:"varint,5,opt,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"`
	// Big-endian u128 for distributed tracing; empty means CorrelationId(0).
	CorrelationId []byte `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Per-edge-connection id (Noise session / fanout routing).
	ConnId        uint64 `protobuf:"varint,7,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHeader) Reset() {
	*x = OrderHeader{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHeader) ProtoMessage() {}

func (x *OrderHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHeader.ProtoReflect.Descriptor instead.
func (*OrderHeader) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{0}
}

func (x *OrderHeader) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *OrderHeader) GetSymbolId() uint64 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

func (x *OrderHeader) GetRequestType() v1.RequestType {
	if x != nil {
		return x.RequestType
	}
	return v1.RequestType(0)
}

func (x *OrderHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *OrderHeader) GetBodyLength() uint32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

func (x *OrderHeader) GetCorrelationId() []byte {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *OrderHeader) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type EncryptedEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Header        *OrderHeader           `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedBody []byte                 `protobuf:"bytes,3,opt,name=encrypted_body,json=encryptedBody,proto3" json:"encrypted_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedEdgeRequest) Reset() {
	*x = EncryptedEdgeRequest{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEdgeRequest) ProtoMessage() {}

func (x *EncryptedEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEdgeRequest.ProtoReflect.Descriptor instead.
func (*EncryptedEdgeRequest) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedEdgeRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEdgeRequest) GetHeader() *OrderHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedEdgeRequest) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (WebSocket fanout / edge routing key).
	UserUuid     []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	MessageType  v1.ResponseMessageType `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=gdx.common.v1.ResponseMessageType" json:"message_type,omitempty"`
	BodyLength   uint32                 `protobuf:"varint,3,opt,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"`
	Nonce        uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FencingEpoch uint64                 `protobuf:"varint,5,opt,name=fencing_epoch,json=fencingEpoch,proto3" json:"fencing_epoch,omitempty"`
	// Big-endian u128 tracing id echoed from the request; empty means CorrelationId(0).
	CorrelationId []byte `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Monotonic per-edge-connection sequence for gap-free ack delivery (Stage 15).
	SessionSeq uint64 `protobuf:"varint,7,opt,name=session_seq,json=sessionSeq,proto3" json:"session_seq,omitempty"`
	// Per-edge-connection id (Noise session / fanout routing).
	ConnId        uint64 `protobuf:"varint,8,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseHeader) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *ResponseHeader) GetMessageType() v1.ResponseMessageType {
	if x != nil {
		return x.MessageType
	}
	return v1.ResponseMessageType(0)
}

func (x *ResponseHeader) GetBodyLength() uint32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

func (x *ResponseHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ResponseHeader) GetFencingEpoch() uint64 {
	if x != nil {
		return x.FencingEpoch
	}
	return 0
}

func (x *ResponseHeader) GetCorrelationId() []byte {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

func (x *ResponseHeader) GetSessionSeq() uint64 {
	if x != nil {
		return x.SessionSeq
	}
	return 0
}

func (x *ResponseHeader) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

type EncryptedEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Header        *ResponseHeader        `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedBody []byte                 `protobuf:"bytes,3,opt,name=encrypted_body,json=encryptedBody,proto3" json:"encrypted_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedEdgeResponse) Reset() {
	*x = EncryptedEdgeResponse{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEdgeResponse) ProtoMessage() {}

func (x *EncryptedEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEdgeResponse.ProtoReflect.Descriptor instead.
func (*EncryptedEdgeResponse) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedEdgeResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEdgeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedEdgeResponse) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

// Stage 15d: edge reconnect resume — replay acks with session_seq > last_applied_seq.
type SessionControl struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LastAppliedSeq uint64                 `protobuf:"varint,1,opt,name=last_applied_seq,json=lastAppliedSeq,proto3" json:"last_applied_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionControl) Reset() {
	*x = SessionControl{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionControl) ProtoMessage() {}

func (x *SessionControl) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionControl.ProtoReflect.Descriptor instead.
func (*SessionControl) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{4}
}

func (x *SessionControl) GetLastAppliedSeq() uint64 {
	if x != nil {
		return x.LastAppliedSeq
	}
	return 0
}

// Noise XK opaque handshake relay (edge stamps user_uuid + conn_id).
type NoiseHandshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"` // 16-byte UUID
	ConnId        uint64                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // opaque Noise message bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseHandshake) Reset() {
	*x = NoiseHandshake{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseHandshake) ProtoMessage() {}

func (x *NoiseHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseHandshake.ProtoReflect.Descriptor instead.
func (*NoiseHandshake) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{5}
}

func (x *NoiseHandshake) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *NoiseHandshake) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *NoiseHandshake) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type NoiseHandshakeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        uint64                 `protobuf:"varint,1,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	Message       []byte                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`          // opaque Noise message bytes
	Established   bool                   `protobuf:"varint,3,opt,name=established,proto3" json:"established,omitempty"` // true when transport is ready (no further handshake msgs)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoiseHandshakeReply) Reset() {
	*x = NoiseHandshakeReply{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoiseHandshakeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoiseHandshakeReply) ProtoMessage() {}

func (x *NoiseHandshakeReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoiseHandshakeReply.ProtoReflect.Descriptor instead.
func (*NoiseHandshakeReply) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{6}
}

func (x *NoiseHandshakeReply) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

func (x *NoiseHandshakeReply) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *NoiseHandshakeReply) GetEstablished() bool {
	if x != nil {
		return x.Established
	}
	return false
}

type SessionClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	ConnId        uint64                 `protobuf:"varint,2,opt,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionClose) Reset() {
	*x = SessionClose{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionClose) ProtoMessage() {}

func (x *SessionClose) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionClose.ProtoReflect.Descriptor instead.
func (*SessionClose) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{7}
}

func (x *SessionClose) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *SessionClose) GetConnId() uint64 {
	if x != nil {
		return x.ConnId
	}
	return 0
}

var File_gdx_edge_v1_edge_proto protoreflect.FileDescriptor

var file_gdx_edge_v1_edge_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x67, 0x64, 0x78, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x64, 0x78, 0x2e, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x64, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x84, 0x02, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64,
	0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x90, 0x01, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x45, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x64, 0x78,
	0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e,
	0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0xb8, 0x02, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x0c, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x65, 0x6e, 0x63,
	0x69, 0x6e, 0x67, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x66, 0x65, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x65, 0x71, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x4a, 0x05,
	0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x94, 0x01, 0x0a, 0x15, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x45, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x33, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x64, 0x78, 0x2e,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x25,
	0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x42, 0x6f, 0x64, 0x79, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x41, 0x0a, 0x0e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x12, 0x28,
	0x0a, 0x10, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x5f, 0x73,
	0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6c, 0x61, 0x73, 0x74, 0x41, 0x70,
	0x70, 0x6c, 0x69, 0x65, 0x64, 0x53, 0x65, 0x71, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22,
	0x60, 0x0a, 0x0e, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x6a, 0x0a, 0x13, 0x4e, 0x6f, 0x69, 0x73, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x6e, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0b, 0x65, 0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x22, 0x44, 0x0a,
	0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x6e, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_gdx_edge_v1_edge_proto_rawDescOnce sync.Once
	file_gdx_edge_v1_edge_proto_rawDescData []byte
)

func file_gdx_edge_v1_edge_proto_rawDescGZIP() []byte {
	file_gdx_edge_v1_edge_proto_rawDescOnce.Do(func() {
		file_gdx_edge_v1_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gdx_edge_v1_edge_proto_rawDesc), len(file_gdx_edge_v1_edge_proto_rawDesc)))
	})
	return file_gdx_edge_v1_edge_proto_rawDescData
}

var file_gdx_edge_v1_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gdx_edge_v1_edge_proto_goTypes = []any{
	(*OrderHeader)(nil),           // 0: gdx.edge.v1.OrderHeader
	(*EncryptedEdgeRequest)(nil),  // 1: gdx.edge.v1.EncryptedEdgeRequest
	(*ResponseHeader)(nil),        // 2: gdx.edge.v1.ResponseHeader
	(*EncryptedEdgeResponse)(nil), // 3: gdx.edge.v1.EncryptedEdgeResponse
	(*SessionControl)(nil),        // 4: gdx.edge.v1.SessionControl
	(*NoiseHandshake)(nil),        // 5: gdx.edge.v1.NoiseHandshake
	(*NoiseHandshakeReply)(nil),   // 6: gdx.edge.v1.NoiseHandshakeReply
	(*SessionClose)(nil),          // 7: gdx.edge.v1.SessionClose
	(v1.RequestType)(0),           // 8: gdx.common.v1.RequestType
	(v1.ResponseMessageType)(0),   // 9: gdx.common.v1.ResponseMessageType
}
var file_gdx_edge_v1_edge_proto_depIdxs = []int32{
	8, // 0: gdx.edge.v1.OrderHeader.request_type:type_name -> gdx.common.v1.RequestType
	0, // 1: gdx.edge.v1.EncryptedEdgeRequest.header:type_name -> gdx.edge.v1.OrderHeader
	9, // 2: gdx.edge.v1.ResponseHeader.message_type:type_name -> gdx.common.v1.ResponseMessageType
	2, // 3: gdx.edge.v1.EncryptedEdgeResponse.header:type_name -> gdx.edge.v1.ResponseHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gdx_edge_v1_edge_proto_init() }
func file_gdx_edge_v1_edge_proto_init() {
	if File_gdx_edge_v1_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gdx_edge_v1_edge_proto_rawDesc), len(file_gdx_edge_v1_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gdx_edge_v1_edge_proto_goTypes,
		DependencyIndexes: file_gdx_edge_v1_edge_proto_depIdxs,
		MessageInfos:      file_gdx_edge_v1_edge_proto_msgTypes,
	}.Build()
	File_gdx_edge_v1_edge_proto = out.File
	file_gdx_edge_v1_edge_proto_goTypes = nil
	file_gdx_edge_v1_edge_proto_depIdxs = nil
}
