// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: gdx/edge/v1/edge.proto

package v1

import (
	v1 "github.com/gq-godark/gdx-go-sdk/proto/gdx/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (edge-authenticated user).
	UserUuid    []byte         `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	SymbolId    uint64         `protobuf:"varint,2,opt,name=symbol_id,json=symbolId,proto3" json:"symbol_id,omitempty"`
	RequestType v1.RequestType `protobuf:"varint,3,opt,name=request_type,json=requestType,proto3,enum=gdx.common.v1.RequestType" json:"request_type,omitempty"`
	Nonce       uint64         `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	BodyLength  uint32         `protobuf:"varint,5,opt,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"`
	// Big-endian u128 for distributed tracing; empty means CorrelationId(0).
	CorrelationId []byte `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderHeader) Reset() {
	*x = OrderHeader{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderHeader) ProtoMessage() {}

func (x *OrderHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderHeader.ProtoReflect.Descriptor instead.
func (*OrderHeader) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{0}
}

func (x *OrderHeader) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *OrderHeader) GetSymbolId() uint64 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

func (x *OrderHeader) GetRequestType() v1.RequestType {
	if x != nil {
		return x.RequestType
	}
	return v1.RequestType(0)
}

func (x *OrderHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *OrderHeader) GetBodyLength() uint32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

func (x *OrderHeader) GetCorrelationId() []byte {
	if x != nil {
		return x.CorrelationId
	}
	return nil
}

type EncryptedEdgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Header        *OrderHeader           `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedBody []byte                 `protobuf:"bytes,3,opt,name=encrypted_body,json=encryptedBody,proto3" json:"encrypted_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedEdgeRequest) Reset() {
	*x = EncryptedEdgeRequest{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEdgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEdgeRequest) ProtoMessage() {}

func (x *EncryptedEdgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEdgeRequest.ProtoReflect.Descriptor instead.
func (*EncryptedEdgeRequest) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedEdgeRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEdgeRequest) GetHeader() *OrderHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedEdgeRequest) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

type ResponseHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (WebSocket fanout / edge routing key).
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	MessageType   v1.ResponseMessageType `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=gdx.common.v1.ResponseMessageType" json:"message_type,omitempty"`
	BodyLength    uint32                 `protobuf:"varint,3,opt,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	FencingEpoch  uint64                 `protobuf:"varint,5,opt,name=fencing_epoch,json=fencingEpoch,proto3" json:"fencing_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseHeader) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *ResponseHeader) GetMessageType() v1.ResponseMessageType {
	if x != nil {
		return x.MessageType
	}
	return v1.ResponseMessageType(0)
}

func (x *ResponseHeader) GetBodyLength() uint32 {
	if x != nil {
		return x.BodyLength
	}
	return 0
}

func (x *ResponseHeader) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ResponseHeader) GetFencingEpoch() uint64 {
	if x != nil {
		return x.FencingEpoch
	}
	return 0
}

type EncryptedEdgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Header        *ResponseHeader        `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	EncryptedBody []byte                 `protobuf:"bytes,3,opt,name=encrypted_body,json=encryptedBody,proto3" json:"encrypted_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedEdgeResponse) Reset() {
	*x = EncryptedEdgeResponse{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedEdgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedEdgeResponse) ProtoMessage() {}

func (x *EncryptedEdgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedEdgeResponse.ProtoReflect.Descriptor instead.
func (*EncryptedEdgeResponse) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{3}
}

func (x *EncryptedEdgeResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EncryptedEdgeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedEdgeResponse) GetEncryptedBody() []byte {
	if x != nil {
		return x.EncryptedBody
	}
	return nil
}

type SessionSetup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (user establishing the E2E session).
	UserUuid         []byte `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	ClientEcdhPubkey []byte `protobuf:"bytes,2,opt,name=client_ecdh_pubkey,json=clientEcdhPubkey,proto3" json:"client_ecdh_pubkey,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionSetup) Reset() {
	*x = SessionSetup{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSetup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSetup) ProtoMessage() {}

func (x *SessionSetup) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSetup.ProtoReflect.Descriptor instead.
func (*SessionSetup) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{4}
}

func (x *SessionSetup) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *SessionSetup) GetClientEcdhPubkey() []byte {
	if x != nil {
		return x.ClientEcdhPubkey
	}
	return nil
}

type SessionEstablished struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SequencerEcdhPubkey []byte                 `protobuf:"bytes,1,opt,name=sequencer_ecdh_pubkey,json=sequencerEcdhPubkey,proto3" json:"sequencer_ecdh_pubkey,omitempty"`
	SessionId           uint64                 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionEstablished) Reset() {
	*x = SessionEstablished{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEstablished) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEstablished) ProtoMessage() {}

func (x *SessionEstablished) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEstablished.ProtoReflect.Descriptor instead.
func (*SessionEstablished) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{5}
}

func (x *SessionEstablished) GetSequencerEcdhPubkey() []byte {
	if x != nil {
		return x.SequencerEcdhPubkey
	}
	return nil
}

func (x *SessionEstablished) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type RekeyRequired struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16-byte RFC 4122 UUID (user whose session must rotate).
	UserUuid      []byte `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	SessionId     uint64 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RekeyRequired) Reset() {
	*x = RekeyRequired{}
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RekeyRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RekeyRequired) ProtoMessage() {}

func (x *RekeyRequired) ProtoReflect() protoreflect.Message {
	mi := &file_gdx_edge_v1_edge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RekeyRequired.ProtoReflect.Descriptor instead.
func (*RekeyRequired) Descriptor() ([]byte, []int) {
	return file_gdx_edge_v1_edge_proto_rawDescGZIP(), []int{6}
}

func (x *RekeyRequired) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *RekeyRequired) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

var File_gdx_edge_v1_edge_proto protoreflect.FileDescriptor

var file_gdx_edge_v1_edge_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x67, 0x64, 0x78, 0x2f, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x67, 0x64, 0x78, 0x2e, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x64, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xeb, 0x01, 0x0a, 0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x64, 0x12, 0x3d, 0x0a, 0x0c, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1a, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x90,
	0x01, 0x0a, 0x14, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x45, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x30, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8,
	0x01, 0x22, 0xd7, 0x01, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x45, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62,
	0x6f, 0x64, 0x79, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x66, 0x65, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x66, 0x65, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x45,
	0x70, 0x6f, 0x63, 0x68, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x94, 0x01, 0x0a, 0x15,
	0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x45, 0x64, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x33, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x67, 0x64, 0x78, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x65, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x4a, 0x05, 0x08, 0x64, 0x10,
	0xc8, 0x01, 0x22, 0x60, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x2c, 0x0a, 0x12, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x63, 0x64, 0x68, 0x5f, 0x70,
	0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x45, 0x63, 0x64, 0x68, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x4a, 0x05, 0x08,
	0x64, 0x10, 0xc8, 0x01, 0x22, 0x6e, 0x0a, 0x12, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45,
	0x73, 0x74, 0x61, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x72, 0x5f, 0x65, 0x63, 0x64, 0x68, 0x5f, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x72, 0x45, 0x63, 0x64, 0x68, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4a, 0x05, 0x08,
	0x64, 0x10, 0xc8, 0x01, 0x22, 0x52, 0x0a, 0x0d, 0x52, 0x65, 0x6b, 0x65, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x4a, 0x05, 0x08, 0x64, 0x10, 0xc8, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_gdx_edge_v1_edge_proto_rawDescOnce sync.Once
	file_gdx_edge_v1_edge_proto_rawDescData []byte
)

func file_gdx_edge_v1_edge_proto_rawDescGZIP() []byte {
	file_gdx_edge_v1_edge_proto_rawDescOnce.Do(func() {
		file_gdx_edge_v1_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gdx_edge_v1_edge_proto_rawDesc), len(file_gdx_edge_v1_edge_proto_rawDesc)))
	})
	return file_gdx_edge_v1_edge_proto_rawDescData
}

var file_gdx_edge_v1_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gdx_edge_v1_edge_proto_goTypes = []any{
	(*OrderHeader)(nil),           // 0: gdx.edge.v1.OrderHeader
	(*EncryptedEdgeRequest)(nil),  // 1: gdx.edge.v1.EncryptedEdgeRequest
	(*ResponseHeader)(nil),        // 2: gdx.edge.v1.ResponseHeader
	(*EncryptedEdgeResponse)(nil), // 3: gdx.edge.v1.EncryptedEdgeResponse
	(*SessionSetup)(nil),          // 4: gdx.edge.v1.SessionSetup
	(*SessionEstablished)(nil),    // 5: gdx.edge.v1.SessionEstablished
	(*RekeyRequired)(nil),         // 6: gdx.edge.v1.RekeyRequired
	(v1.RequestType)(0),           // 7: gdx.common.v1.RequestType
	(v1.ResponseMessageType)(0),   // 8: gdx.common.v1.ResponseMessageType
}
var file_gdx_edge_v1_edge_proto_depIdxs = []int32{
	7, // 0: gdx.edge.v1.OrderHeader.request_type:type_name -> gdx.common.v1.RequestType
	0, // 1: gdx.edge.v1.EncryptedEdgeRequest.header:type_name -> gdx.edge.v1.OrderHeader
	8, // 2: gdx.edge.v1.ResponseHeader.message_type:type_name -> gdx.common.v1.ResponseMessageType
	2, // 3: gdx.edge.v1.EncryptedEdgeResponse.header:type_name -> gdx.edge.v1.ResponseHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gdx_edge_v1_edge_proto_init() }
func file_gdx_edge_v1_edge_proto_init() {
	if File_gdx_edge_v1_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gdx_edge_v1_edge_proto_rawDesc), len(file_gdx_edge_v1_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gdx_edge_v1_edge_proto_goTypes,
		DependencyIndexes: file_gdx_edge_v1_edge_proto_depIdxs,
		MessageInfos:      file_gdx_edge_v1_edge_proto_msgTypes,
	}.Build()
	File_gdx_edge_v1_edge_proto = out.File
	file_gdx_edge_v1_edge_proto_goTypes = nil
	file_gdx_edge_v1_edge_proto_depIdxs = nil
}
